# flake8: noqa
from . import adding_and_removing_elements
from .adding_and_removing_elements import *
from . import basic_operations
from .basic_operations import *
from . import changing_array_shape
from .changing_array_shape import *
from . import changing_kind_of_array
from .changing_kind_of_array import *
from . import changing_number_of_dimensions
from .changing_number_of_dimensions import *
from . import joining_arrays
from .joining_arrays import *
from . import rearranging_elements
from .rearranging_elements import *
from . import splitting_arrays
from .splitting_arrays import *
from . import tiling_arrays
from .tiling_arrays import *
from . import transpose_like_operations
from .transpose_like_operations import *
