---
listing:

    - id: learn-the-basics
      template: assets/ejs/gallery.ejs
      contents:
        - "learn_the_basics/01_write_ivy_code.ipynb"
        - "learn_the_basics/02_unify_code.ipynb"
        - "learn_the_basics/03_compile_code.ipynb"
        - "learn_the_basics/04_transpile_code.ipynb"
        - "learn_the_basics/05_lazy_vs_eager.ipynb"
        - "learn_the_basics/06_how_to_use_decorators.ipynb"
        - "learn_the_basics/07_transpile_any_library.ipynb"
        - "learn_the_basics/08_transpile_any_model.ipynb"
      sort: "false"

    - id: guides
      template: assets/ejs/gallery.ejs
      contents:
        - "guides/01_transpiling_a_torch_model.ipynb"
        - "guides/03_transpiling_a_tf_model.ipynb"
      sort: "false"

    - id: examples-and-demos
      template: assets/ejs/gallery.ejs
      contents:
        - "examples_and_demos/resnet_demo.ipynb"
        - "examples_and_demos/torch_to_jax.ipynb"
        - "examples_and_demos/mmpretrain_to_jax.ipynb"
        - "examples_and_demos/image_segmentation_with_ivy_unet.ipynb"
        - "examples_and_demos/alexnet_demo.ipynb"
      sort: "false"
---

## Tutorials and Examples

Welcome to Ivy's tutorials webpage! Our goal is to provide you with a comprehensive learning experience on a variety of topics. We have organized our tutorials into three main sections to help you find exactly what you need. 

If you are in a rush, you can jump straight into the **[Quickstart](quickstart.ipynb)**, a quick and general introduction to Ivy's features and capabilities!

- In the **Learn the basics** section, you will find basic and to the point tutorials to help you get started with Ivy.

- The **Guides** section includes more involved tutorials for those who want to dive deeper into the framework. 

- Finally, in the **Examples and Demos** section, you will find start-to-finish projects and applications that showcase real-world applications of Ivy. Whether you're a beginner or an advanced user, we've got you covered!

::: {.callout-tip appearance="minimal"}
<span style="color:#35a835;">Note:</span> Want to use Ivy locally? Check out the [Get Started section of the docs!](https://unify.ai/docs/ivy/overview/get_started.html)
:::

### Learn the basics
:::{#learn-the-basics}
:::

### Guides
:::{#guides}
:::

### Examples and Demos
:::{#examples-and-demos}
:::