from ivy.transpiler.transformations.transformers.rename_transformer import base_transformer
from ivy.transpiler.transformations.transformers.rename_transformer.base_transformer import BaseRenameTransformer
