#!/bin/bash
# file to setup documentation building pipeline without docker
# $1 : Path to the doc-builder folder relative to the ivy/docs folder

# install libraries for the doc-builder
cat $1/requirements.txt | xargs -n 1 pip install;

# install libraries for ivy
pip install -r ../requirements/requirements.txt || exit 1
pip install torch==1.11.0
pip install torch-scatter==2.0.9
if [[ $(arch) == 'arm64' ]]; then
  pip install -r ../requirements/optional_m1_1.txt || exit 1
  pip install -r ../requirements/optional_m1_2.txt || exit 1
else
  pip install -r ../requirements/optional.txt || exit 1
fi

# syncing ivy folder with the doc-builder folder
rsync -rav $1/docs/ . || exit 1

# Delete any previously generated content
rm -rf autogenerated_source

# delete any previously generated pages
rm -rf build

# generate content
python generate_src_rst_files.py  --root_dir ../ivy || exit 1

# generate pages from content
python sphinx-build.py -Q -b html autogenerated_source build || exit 1

python correct_built_html_files.py || exit 1

# delete the code
bash remove_files.sh
rm -rf remove_files.sh
