name: 'Auto Assign'
on:
  pull_request:
    types: [opened]
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign.yml'
