name: Review Assign

on:
  pull_request:

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: Sam-Armstrong, hmahmood24, YushaArif99
          max-num-of-reviewers: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}
