name: Build Dockerfile

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [labeled]
    branches: [ "master" ]

jobs:

  build:
    
    runs-on: ubuntu-20.04

    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: with CI
          repo_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build Dockerfile
      run: docker build . --file Dockerfile --tag unifyai/ivy:$(date +%s)
