name: Dockerfile MultiCUDA Push

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 🛎 Ivy
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Dockerfile
        run: |
          docker build --progress=plain --no-cache -t unifyai/multicuda:base_and_requirements -f docker/DockerfileGPUMultiCuda ..
          docker push unifyai/multicuda:base_and_requirements
