name: Build Dockerfile

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [labeled, review_requested]
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build Dockerfile
      run: docker build . --file Dockerfile --tag unifyai/ivy:$(date +%s)
