name: Build Dockerfile Schedule

on:
  # schedule:
  #   # run at every 5 mins
  #   - cron:  '*/5 * * * *'
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push Dockerfile
      run: |
        docker build . --file Dockerfile --tag unifyai/ivy:latest
        docker push unifyai/ivy:latest

    - name: Build and push DockerfileCopsim
      run: |
        docker build . --file DockerfileCopsim --tag unifyai/ivy:latest-copsim
        docker push unifyai/ivy:latest-copsim
        
