name: run-all-tests
on:
  workflow_dispatch:

permissions:
  actions: read
jobs:
  display_test_results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - run_tests

    steps:
      - name: Download all test results
        uses: actions/download-artifact@v3

      - name: Combined Test Results
        run: |
          find . -name "test_results_*.txt" -exec cat {} + > combined_test_results.txt
          echo "Test results summary:"
          cat combined_test_results.txt

  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                  11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
                  21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
                  31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
                  41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
                  51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
                  61, 62, 63, 64 ]
    steps:
      - name: Checkout Ivy 🛎
        uses: actions/checkout@v3
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 100

      - name: Install ivy and fetch binaries
        run: |
          cd ivy
          sudo pip3 install -e .
          mkdir .ivy
          touch .ivy/key.pem
          echo -n ${{ secrets.USER_API_KEY }} > .ivy/key.pem
          cd ..

      - name: Get Job URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Run Tests
        run: |
          pip3 install pymongo
          cd ivy
          python scripts/setup_tests/filter_tests.py ${{ matrix.branch }}
          set -o pipefail
          python scripts/run_tests/run_tests.py ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD }} ${{ secrets.MONGODB_PASSWORD }} 'false' 'false' ${{ github.run_id }} 'false' 'false' 'false' ${{ steps.jobs.outputs.html_url }} | tee test_results_${{ matrix.branch }}.txt
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test_results_${{ matrix.branch }}
          path: ivy/test_results_${{ matrix.branch }}.txt

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
